theme: minima
title: "APHA 2022 Poster: Parent Mental Health"
author:
  name: Nicholas Griffiths
  email: ngg@bu.edu
description: >
  Online content to go with the poster presented at APHA
minima:
  # generate social links in footer
  social_links:
    github: ngriffiths21
header-pages:
